- name: Copy in usb-mount.sh (script for automounting USB)
  become: yes
  copy:
    src: files/usb-mount.sh
    dest: /usr/local/bin/usb-mount.sh
    mode: '755'

- name: Copy in systemd unit file for USB automount/unmount
  become: yes
  copy:
    src: files/usb-mount@.service
    dest: /etc/systemd/system/usb-mount@.service

- name: Create udev rule to start/stop usb-mount@.service on hotplug/unplug
  become: yes
  blockinfile:
    path: /etc/udev/rules.d/99-local.rules
    create: yes
    block: |
      KERNEL=="sd[a-z]*[0-9]", SUBSYSTEMS=="usb", ACTION=="add", RUN+="/bin/systemctl start usb-mount@%k.service"
      KERNEL=="sd[a-z]*[0-9]", SUBSYSTEMS=="usb", ACTION=="remove", RUN+="/bin/systemctl stop usb-mount@%k.service"

- name: Ensure services are unmasked, enabled, and restarted.
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: restarted
    daemon_reload: yes
  loop:
    - dhcpcd
    - hostapd
    - dnsmasq
    - nginx
    - kolibri-server

- name: Reload the udev rules
  become: yes
  shell:
    udevadm control --reload-rules